<a href="https://colab.research.google.com/github/KRCS2026/DATA-SCIENCE-JOURNEY/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
scores = [85, 90, 78, 92, 88]

total = sum(scores)
average = total / len(scores)

print("মোট নম্বর:", total)
print("গড় নম্বর:", average)

মোট নম্বর: 433
গড় নম্বর: 86.6


In [2]:
students = {
    "Rahim": 78,
    "Karim": 92,
    "Salma": 85,
    "Nadia": 65
}

def grade_checker(score):
    if score >= 90:
        return "A+"
    elif score >= 80:
        return "A"
    else:
        return "Needs Improvement"

for name, score in students.items():
    grade = grade_checker(score)
    print(name, "-", score, "-", grade)

Rahim - 78 - Needs Improvement
Karim - 92 - A+
Salma - 85 - A
Nadia - 65 - Needs Improvement


In [11]:
students = {
  "rahim": 89,
  "karim": 45,
  "arman": 73,
  "sadik": 93,

}

def grades(score):
  if score >90:
    return "A+"
  elif score >=80:
    return "A"
  else: return "needs improvement"

for students, score in students.items():
  grade = grades(score)
  print(students, "-", score, "-",grade)


rahim - 89 - A
karim - 45 - needs improvement
arman - 73 - needs improvement
sadik - 93 - A+


In [2]:
scores = [34, 2344, 4234, 5345, 53453]
total = sum(scores)
average = total/len(scores)
print("total sum", total)
print("average is",average)

total sum 65410
average is 13082.0


In [13]:
import numpy as np

In [14]:
scores = np.array([85, 90, 78, 92, 88])

print("গড়:", np.mean(scores))
print("সর্বোচ্চ:", np.max(scores))
print("সর্বনিম্ন:", np.min(scores))
print("স্ট্যান্ডার্ড ডিভিয়েশন:", np.std(scores))
print("সর্টেড:", np.sort(scores))

গড়: 86.6
সর্বোচ্চ: 92
সর্বনিম্ন: 78
স্ট্যান্ডার্ড ডিভিয়েশন: 4.882622246293481
সর্টেড: [78 85 88 90 92]


In [20]:
marks = np.array([

    [85, 90, 78],
    [92, 88, 95],
    [70, 65, 80]
])

print("প্রতি স্টুডেন্টের গড়:", np.mean(marks, axis=1))
print("প্রতি সাবজেক্টের গড়:", np.mean(marks, axis=0))

print("গড়:", np.mean(marks))
print("সর্বোচ্চ:", np.max(marks))
print("সর্বনিম্ন:", np.min(marks))
print("স্ট্যান্ডার্ড ডিভিয়েশন:", np.std(marks))
print("সর্টেড:", np.sort(marks))


প্রতি স্টুডেন্টের গড়: [84.33333333 91.66666667 71.66666667]
প্রতি সাবজেক্টের গড়: [82.33333333 81.         84.33333333]
গড়: 82.55555555555556
সর্বোচ্চ: 95
সর্বনিম্ন: 65
স্ট্যান্ডার্ড ডিভিয়েশন: 9.592950086288612
সর্টেড: [[78 85 90]
 [88 92 95]
 [65 70 80]]


In [29]:
mark = np.array([

      [12,13, 15],
      [14, 13, 11],
      [15,11,13],

]
)

print("gor",np.mean(mark) )
print("shorboccho", np.max(mark))
print("shorbonimno", np.min(mark))
print("std", np.std(mark))
print("sort", np.sort(mark))
print("column wise",np.max(mark, axis=0) )
print("row wise",np.max(mark, axis=1))

gor 13.0
shorboccho 15
shorbonimno 11
std 1.4142135623730951
sort [[12 13 15]
 [11 13 14]
 [11 13 15]]
column wise [15 13 15]
row wise [15 14 15]


In [30]:
import pandas as pd

In [40]:
data = {
    "Name": ["Rahim", "Karim", "Salma", "Nadia"],
    "Age": [22, 25, 21, 23],
    "Score": [78, 92, 85, 65],
    "City": ["Dhaka", "Chittagong", "Dhaka", "Sylhet"],
    "area": ["Dhaka", "Chittagong", "Dhaka", "Sylhet"],
    "City2": ["Dhaka", "Chittagong", "Dhaka", "Sylhet"]
}

df = pd.DataFrame(data)


print(df.head())
print(df.shape)
print(df.columns)
print(df.describe())



    Name  Age  Score        City        area       City2
0  Rahim   22     78       Dhaka       Dhaka       Dhaka
1  Karim   25     92  Chittagong  Chittagong  Chittagong
2  Salma   21     85       Dhaka       Dhaka       Dhaka
3  Nadia   23     65      Sylhet      Sylhet      Sylhet
(4, 6)
Index(['Name', 'Age', 'Score', 'City', 'area', 'City2'], dtype='object')
             Age      Score
count   4.000000   4.000000
mean   22.750000  80.000000
std     1.707825  11.518102
min    21.000000  65.000000
25%    21.750000  74.750000
50%    22.500000  81.500000
75%    23.500000  86.750000
max    25.000000  92.000000
