<a href="https://colab.research.google.com/github/K-REDWAN/DATA-SCIENCE-JOURNEY/blob/main/Practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("যোগ:\n", A * B)

result = np.matmul(A, B)
print(result)

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)

I = np.identity(3)
print(I)

যোগ:
 [[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 4]
 [2 5]
 [3 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
from scipy import stats
import numpy as np

old_method = np.array([65, 70, 68, 72, 69, 71, 66])
new_method = np.array([75, 78, 80, 76, 82, 79, 77])

t_stat, p_value = stats.ttest_ind(old_method, new_method)

print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print("পার্থক্যটা statistically significant — নতুন পদ্ধতি সত্যিই আলাদা ফল দিচ্ছে")
else:
    print("যথেষ্ট প্রমাণ নেই, পার্থক্যটা কাকতালীয়ও হতে পারে")

t-statistic: -7.089537252990388
p-value: 1.2659564973227654e-05
পার্থক্যটা statistically significant — নতুন পদ্ধতি সত্যিই আলাদা ফল দিচ্ছে


In [ ]:
from scipy import stats

n = 10       # মোট ট্রায়াল
p = 0.5      # প্রতিবার হেড আসার সম্ভাবনা

# ঠিক ৫ বার হেড আসার সম্ভাবনা কত?
prob_5_heads = stats.binom.pmf(5, n, p)
print("ঠিক ৫ বার হেড আসার সম্ভাবনা:", prob_5_heads)

ঠিক ৫ বার হেড আসার সম্ভাবনা: 0.24609375000000003


In [ ]:
n = 10
p = 0.25

for correct in range(0, 11):
    prob = stats.binom.pmf(correct, n, p)
    print(f"{correct}টা সঠিক হওয়ার সম্ভাবনা: {prob:.4f}")

0টা সঠিক হওয়ার সম্ভাবনা: 0.0563
1টা সঠিক হওয়ার সম্ভাবনা: 0.1877
2টা সঠিক হওয়ার সম্ভাবনা: 0.2816
3টা সঠিক হওয়ার সম্ভাবনা: 0.2503
4টা সঠিক হওয়ার সম্ভাবনা: 0.1460
5টা সঠিক হওয়ার সম্ভাবনা: 0.0584
6টা সঠিক হওয়ার সম্ভাবনা: 0.0162
7টা সঠিক হওয়ার সম্ভাবনা: 0.0031
8টা সঠিক হওয়ার সম্ভাবনা: 0.0004
9টা সঠিক হওয়ার সম্ভাবনা: 0.0000
10টা সঠিক হওয়ার সম্ভাবনা: 0.0000
